title: Research With Consent
description: Resources for fieldwork ethics, safety, and documentation rights
markdown: kramdown
baseurl: "/GoldenTrowelProject" # leave empty unless your site is in a subfolder
url: "https://anthrosafetywarrior.github.io/GoldenTrowelProject" # your GitHub Pages URL
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:name.html
