title: Golden Trowel Project
description: Resources for fieldwork ethics, safety, and documentation rights

url: "https://goldentrowelproject.org"   # your custom domain
baseurl: ""                              # empty for custom domain

markdown: kramdown
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:name.html
